backend:
  name: git-gateway
  branch: flyer-updated

media_folder: "static/uploads"
public_folder: "uploads"


collections:
  - name: "flyer"
    label: "Flyer"
    folder: "content/flyers"
    create: true
    slug: "{{title}}"
    preview_path: "flyer/{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Title Days", name: "titledays", widget: "string", required: true}
      - {label: "Path", name: "path", widget: "string", required: true, default: "/flyer/"}
      - {label: "Price", name: "price", widget: "number", required: true}
      - label: "Price Description"
        name: "pricedesc"
        widget: "list"
        default: ["per person", "min 2 to go"]
      - {label: "Header Image", name: "headerimg", widget: "image", required: true}
      - {label: "Header Title", name: "headertitle", widget: "string", required: true}
      - {label: "Header Description", name: "headerdesc", widget: "string", required: true}
      - {label: "Tour Code", name: "tourcode", widget: "string", required: true}
      - label: "Quick Info" 
        name: "quickinfo"
        widget: "list"
        fields: 
          - {label: Text, name: text, widget: string, default: "tour guide included"}
          - {label: Icon, name: icon, widget: image}
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        fields: 
          - {label: Title, name: title, widget: string, default: "Block title"}
          - label: "Block Items"
            name: "blockitems"
            widget: "list"
            default: ["item 1", "item 2"]
      - label: "Itinerary"
        name: "itinerary"
        widget: "list"
        fields: 
          - {label: Day Number, name: daynumber, widget: number}
          - {label: Day Title, name: daytitle, widget: string, default: "Arrival - Brunei"}
          - {label: Meals, name: mealsincluded, widget: string, default: "Breakfast, Lunch and Dinner"}
          - label: "Items"
            name: "items"
            widget: "list"
            fields: 
              - {label: Not Bold, name: notbold, widget: string, default: "Visit"}
              - {label: Bold, name: bold, widget: string, default: "Bandar Seri Begawan"}
      - label: "Places of Interest" 
        name: "poi"
        widget: "list"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Description, name: desc, widget: string}
          - {label: Image, name: image, widget: image}
      


