backend:
  name: git-gateway
  branch: flyer

media_folder: "static/uploads"
public_folder: "uploads"


collections:
  - name: "flyer"
    label: "Flyer"
    folder: "content/flyers"
    create: true
    slug: "{{title}}"
    preview_path: "flyer/{{title}}"
    fields:
      - {label: "Path", name: "path", widget: "string", required: true, default: "/flyer/"}
      - {label: "Price", name: "price", widget: "number", required: true}
      - {label: "Price Description", name: "pricedesc", widget: "string", required: true}
      - {label: "Flyer Title", name: "flyertitle", widget: "string", required: true}
      - {label: "Header Image", name: "headerimg", widget: "image", required: true}
      - {label: "Header Title", name: "headertitle", widget: "string", required: true}
      - {label: "Header Description", name: "headerdesc", widget: "string", required: true}
      - {label: "Tour Code", name: "tourcode", widget: "string", required: true}
      - label: "Quick Info" 
        name: "quickinfo"
        widget: "list"
        fields: 
          - {label: Text, name: text, widget: string, default: "tour guide included"}
          - {label: Icon, name: icon, widget: image}


