backend:
  name: git-gateway
  branch: flyer

media_folder: "static/uploads"
public_folder: "uploads"


collections:
  - name: "flyer"
    label: "Flyer"
    folder: "content/flyers"
    create: true
    slug: "{{title}}"
    preview_path: "flyer/{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Path", name: "path", widget: "string", required: true, default: "/flyer/"}
      - {label: "Price", name: "price", widget: "number", required: true}
      - label: "Price Description"
        name: "pricedesc"
        widget: "list"
        default: ["per person", "min 2 to go"]
      - {label: "Header Image", name: "headerimg", widget: "image", required: true}
      - {label: "Header Title", name: "headertitle", widget: "string", required: true}
      - {label: "Header Description", name: "headerdesc", widget: "string", required: true}
      - {label: "Tour Code", name: "tourcode", widget: "string", required: true}
      - label: "Quick Info" 
        name: "quickinfo"
        widget: "list"
        fields: 
          - {label: Text, name: text, widget: string, default: "tour guide included"}
          - {label: Icon, name: icon, widget: image}
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        fields: 
          - {label: Title, name: title, widget: string, default: "Block title"}
          - label: "Block Items"
            name: "blockitems"
            widget: "list"
            default: ["item 1", "item 2"]


